### ISSUE TITLE
update for flatpak

### ISSUE THREAD

**Issue by cassop** [mufeedali/Wordbook#43]
* Wordbook version: 0.31
* Operating system: fedora 37

The current status of the app from this repo is awesome which brought many changes. But the app from flathub is too old. Although it's functional some bugs like issue [#33](https://github.com/fushinari/Wordbook/issues/33) are still there.

Frankly many people, like me, would be excited to see it out on flathub.

**Comment by jn64** [comment]
I built a rpm of latest Wordbook on Copr. It's just a one-off build for my own use, I don't have the time to maintain it. I also use the repo for testing other packages, so I strongly recommend disabling the repo after installing.

Please review the spec file and SRPMs (in the F37 chroots below) before installing from an unknown source.

- Wordbook
  - https://copr.fedorainfracloud.org/coprs/jn64/playground/build/5343676/
- python3-wn (had to build it as well, since it's not in Fedora repos)
  - https://copr.fedorainfracloud.org/coprs/jn64/playground/build/5343387/

```sh
# dnf copr enable jn64/playground
# dnf install Wordbook
# dnf copr disable jn64/playground
```

Note the database and config will be in `~/.local/share/wordbook` and `~/.config/wordbook`, unlike the flatpak's in `~/.var/app/com.github.fushinari.Wordbook/...`

**Comment by xplosionmind** [comment]
+1… Flatpak is not “yet another packaging system to use”, but it is the future of cross-distro apps release! It would be really, really important not to leave it behind, especially with [GNOME dictionary repo being archived](https://gitlab.gnome.org/Archive/gnome-dictionary).

**Comment by mufeedali** [comment]
To be very clear, I don't see flatpak as "yet another packaging system to use". It's the only official package for it.

I just have a job and a life and haven't been able to find time to solve some issues in the current branch. For example, the appearance of the autocomplete feature. I do plan to make a release of the current branch with some minor changes soon anyway though because as the reporter noted, there are some important changes in the current branch.
